services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dservices-socket
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - global-network
    volumes:
      - .:/app
      - /app/node_modules
networks:
    global-network:
        external: true
